version: '3.8'
services:

  mysql:
    container_name: mysql1
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password

  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
